### PR TITLE
Pin the local 'blurhash/index.js' to 'active_storage_blurhash' in ord…

### LINKED ISSUE #7: The "./blurhash" import in application.js is not working properly with importmap
When installing the gem, the installation generator pins the blurhash library to the 'blurhash' namespace and then copies the actual front-end code to “app/javascript/blurhash” and then appends the import to the main entry point:

```ruby
def install_javascript_deps
  if File.exist? Rails.root.join("config", "importmap.rb")
    say "Pinning blurhash"
    run "bin/importmap pin blurhash"
  else
    say "Installing blurhash"
    run "yarn add blurhash"
  end
end

def copy_application_javascript
  directory "javascript", "app/javascript/blurhash"
end

def append_to_main_javascript_entrypoint
  append_to_file "app/javascript/application.js", "import \"./blurhash\";\n"
end
```

However, when using importmap, the `import "./blurhash"` fails with `GET http://localhost:3000/assets/blurhash net::ERR_ABORTED 404 (Not Found)`.

As far as I can tell, that might be because we're not actually pinning that file to be available to import it from `application.js`.

### PR DESCRIPTION
**Pull request by erozas**
This PR fixes #7 where, by default, the actual JS code wouldn't load because it wasn't being pinned when using import maps.

It:

- Adds an entry to `importmap.rb` to pin `active_storage_blurhash` to `blurhash/index` within `app/javascript`.
- Replaces the previous `import "./blurhash"` with `import "./active_storage_blurhash"` to avoid any potential name conflict with the blurhash library.

I tested the changes in a dummy application with an out-of-the box install of 'active_storage-blurhash' and it works:

active_storage_blurhash_test

### CODE REVIEW

File: lib/generators/active_storage/blurhash/install/install_generator.rb [hunk 1]
```diff
@@ -15,7 +15,13 @@ def copy_application_javascript
...
 
+  def pin_blurhash_javascript
+    if File.exist? Rails.root.join("config", "importmap.rb")
+      append_to_file "config/importmap.rb", 'pin "active_storage_blurhash", to: "blurhash/index.js"' + "\n"
+    end
+  end
+
   def append_to_main_javascript_entrypoint
-    append_to_file "app/javascript/application.js", "import \"./blurhash\";\n"
+    append_to_file "app/javascript/application.js", "import \"active_storage_blurhash\";\n"
```
Comment (julianrubisch) [inline lib/generators/active_storage/blurhash/install/install_generator.rb:25]: I think we need to be more careful here, because this would break non-importmap applications who have no knowledge of an `active_storage_blurhash` package.

Maybe add a switch like this? 
https://github.com/avo-hq/active_storage-blurhash/pull/8/files#diff-6e19a81d79f6d19aa21abc1fb51d1cb233afbdae097f2b9758a77dbaafc12408L5

Note that @adrianthedev and me opted against making this a Javascript package of its own right, though we might want to reconsider this at some point 🤔

**Review by julianrubisch — CHANGES_REQUESTED** [review]
